<?php
namespace Common\Basic;

class DataType{
	static $type=array(
				1=>array('table'=>'Package','name'=>'套餐'),
				2=>array('table'=>'Product','name'=>'销售品',
							'field'=>array(
								'product_name',//销售品名称
								'product_code',//销售品编号
								'city',//地市
								'business_code',//集团业务编码
								'product_type',//销售品类型
								'product_cat',//销售品分类
								'product_packname',//销售品包装名称
								'product_alias',//销售品别名
								'customer_brand',//客户名牌
								'business_brand',//业务品牌
								'product_catalog',//销售品目录
								'product_group',//归属销售品组
								'manage_level',//管理级别
								'manage_department',//管理部门
								'poster_name',//发布人
								'operater_code',//操作工号
								'available_start',//生效时间
								'available_end',//失效时间
								'onsale_time',//上市时间
								'onsale_status',//上市状态
								'version',//在用版本
								'current_status',//当前状态
								'pay_type',//付费方式
								'dynamic_month',//动态月结
								'can_renew',//允许续约
								'can_alone',//可独立销售
								'cacel_on_mutex',//互斥时自动取消
								'is_plugin',//是否加装
								'product_content',//销售品描述
								'fee_brief',//资费描述
								'sale_places',//销售阵地
								'acceptance_time',//受理时间
								'acceptance_number',//受理量
								'stop_auto',//是否自动停售
							)
				),
				3=>array('table'=>'Pikai','name'=>'批开',
							'field'=>array(
								'pikai_item',//批开项目
								'pikai_file_name',//文件名
								'city',//城市
								'batch_number',//批次号
								'phone_number',//号码
								'card_number',//NIM卡号
								'acceptance_time',//受理时间
								'acceptance_status',//受理状态
								'package_name',//套餐名称
								'product_code',//主套餐编号
								'product_name',//住套餐名称
								'opar_code',//受理工号
								'puka_time',//铺卡时间
								'puka_net'//铺卡网点
							)
				),
				
				4=>array('table'=>'Number','name'=>'省CRM',
							'field'=>array(
								'number_code',//号码
								'sys_from',//管理系统
								'city',//地市
								'pre_pay',//预存费用
								'min_resume',//最低消费
								'number_level',//号码等级
								'number_status',//号码状态
								'pool_name',//号码池名称
								'status_time',//状态日期
								'remark',//备注
								'holder_type',//预存对象类型
								'customer_name',//客户名称
								'holder_name',//预存对象名称
								'holder_identify',//预存对象标示
								'holder_expire',//预存截止日期
								'data_type',//数据类型
								'switchboard',//交换机名称
								'service_identify',//服务标示
								'local_net',//本地网
								'net_identify',//网络标示
								'number_prefix',//手机号前3位
								'number_prefix2',//手机号前7位
								'control_prefix',//管控号段
								'quality',//品质分类
								'label',//标签
								'use_time',//使用时间
								'use_type',//使用去向
								'use_person',//使用人					
								
							)
				),
				
				5=>array('table'=>'Number','name'=>'集用4G营业门户',
							'field'=>array(
								'number_code',//号码
								'sys_from',//管理系统
								'pool_name',//号码池名称
								'province',//省份
								'belong_region',//归属地区
								'number_status',//状态
								'number_level',//号码等级
								'min_resume',//保底金额
								'pre_pay',//预存款
								'min_resume_old',//原保底金额
								'pre_pay_old',//原预存款
								'create_time',//创建时间
								'number_prefix',//手机号前3位
								'number_prefix2',//手机号前7位
								'control_prefix',//管控号段
								'quality',//品质分类
								'label',//标签
								'use_time',//使用时间
								'use_type',//使用去向
								'use_person',//使用人
							)
				),
				6=>array('table'=>'Card','name'=>'集用4G后付费卡',
							'field'=>array(
								'cat_name',//项目名称
								'card_code',//卡片编号
								'city',//所属地市
								'number_prefix',//手机前3位
								'card_size',//卡尺寸
								'net_type',//网络制式
								'pay_type',//付费类型
								'made_by',//制卡系统
								'supplier',//主办供应商
								'card_status',//卡状态
								'sheet_code',//制卡工单号
								'stock_place',//入库分派仓位
								'stock_cat',//入库分类编码
								'stocked_time',//完成入库时间
								'allot_brief',//分派使用说明
								'attachment',//入库附件名称
								'stock_time',//入库日期
								'is_iscn',//是否已录入ISCN
								'stock_name',//调库名称
								'stock_name1',//调库前仓位1次
								'stock_name2',//调库前仓位2次
							)
				),
				7=>array('table'=>'Card','name'=>'集团天翼小白',
							'field'=>array(
								'cat_name',//项目名称
								'card_code',//卡片编号
								'city',//所属地市
								'number_prefix',//手机前3位
								'card_size',//卡尺寸
								'net_type',//网络制式
								'pay_type',//付费类型
								'imsi',//IMSI
								'puk',//PUK
								'made_by',//制卡系统
								'supplier',//主办供应商
								'card_status',//卡状态
								'sheet_code',//制卡工单号
								'expire_time',//失效时间
								'stock_place',//入库分派仓位
								'stock_cat',//入库分类编码
								'stocked_time',//完成入库时间
								'allot_brief',//分派使用说明
								'attachment',//入库附件名称
								'stock_time',//入库日期																													
							)
				),
				8=>array('table'=>'Card','name'=>'集团天程写卡',
							'field'=>array(
								'cat_name',//项目名称
								'card_code',//卡片编号
								'city',//所属地市
								'number_prefix',//手机前3位
								'card_size',//卡尺寸
								'net_type',//网络制式
								'made_by',//制卡系统
								'supplier',//主办供应商
								'pay_type',//付费类型
								'card_status',//卡状态
								'sheet_code',//制卡工单号
								'stock_place',//入库分派仓位
								'stock_cat',//入库分类编码
								'stocked_time',//完成入库时间
								'allot_brief',//分派使用说明
								'attachment',//入库附件名称
								'stock_time',//入库日期
								'stock_name',//调库名称																						
							)
				),
				9=>array('table'=>'Card','name'=>'预付费卡',
							'field'=>array(
								'cat_name',//项目名称
								'card_code',//卡片编号
								'number_code',//号码
								'city',//所属地市
								'number_prefix',//手机前3位
								'card_size',//卡尺寸
								'net_type',//网络制式
								'made_by',//制卡系统
								'supplier',//主办供应商
								'pay_type',//付费类型
								'card_status',//卡状态
								'sheet_code',//制卡工单号
								'stock_place',//入库分派仓位
								'stock_cat',//入库分类编码
								'stocked_time',//完成入库时间
								'allot_brief',//分派使用说明
								'attachment',//入库附件名称
								'stock_time',//入库日期
								'package_name',//批开套餐名称
								'expire_time',//失效时间
								'has_pack',//是否有包装
								'time_on_pack',//包装上的过期时间
								'puka_brief',//铺卡情况								
								'stock_name',//调库名称
								'stock_name1',//调库前仓位1次
								'stock_name2',//调库前仓位2次
								'is_iscn',//是否已录入ISCN
								'out_sheet_name',//出库单名称
								'out_sheet_time',//出库单时间	
							)
				),
			);
	
	public function ReturnType($big_key,$small_key,$field,$cat){
		$cat_array=array(
							1=>array(1),
							2=>array(2),
							3=>array(3),
							4=>array(4,5),
							5=>array(6,7,8,9)
						);
		$type_list=self::$type;
		
		if($big_key!='' && $small_key!=''){
			return $type_list[$big_key][$small_key];
		}elseif($big_key!=''){
			return $type_list[$big_key];
		}
		
		if($field!=''){
			foreach($type_list as $key=>$val){
				$new_type_list[$key]=$val[$field];
			}
			if(intval($cat)>0){
				foreach($new_type_list as $key=>$val){	
					if(!in_array($key,$cat_array[$cat])){
						unset($new_type_list[$key]);	
					}
				}
			}
			
			return $new_type_list;
		}
		
		return $type_list;
	}
	
}
